# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT usla.wsgi

beta_settings:
    cloud_sql_instances: usla-app:us-east4:usla-data

runtime_config:
  python_version: 3
# [END runtime]
