# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:16
from __future__ import unicode_literals

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')])),
                ('cel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')])),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_members_to_images)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardPositions',
            fields=[
                ('title', models.CharField(default='The Title', max_length=100, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeChairPositions',
            fields=[
                ('title', models.CharField(default='The Title', max_length=100, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')])),
                ('cel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')])),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_members_to_images)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CommitteeChairPositions')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Event Name', max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, choices=[('LA', 'USLA Pavilion'), ('LB', 'Irwin Inn Beach'), ('LC', "Crowe's Landing Docks"), ('LD', 'Multiple'), ('LE', None)], max_length=2)),
                ('unique_location', models.CharField(blank=True, max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('cost_has_hst', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='images/events/')),
                ('pdf_file', models.FileField(blank=True, upload_to='files/events/')),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('title_text', models.CharField(default='The Title', max_length=50, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, default='url', max_length=50)),
                ('fa_icon', models.CharField(blank=True, max_length=30)),
                ('sub_description', models.CharField(default='The Title Description', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_to_pages)),
                ('description', models.TextField(default='Page Description')),
                ('page_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='UNIQUE_NAME', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_program_to_images)),
                ('pdf_file', models.FileField(blank=True, upload_to=app.models.get_upload_program_to_files)),
                ('fa_icon', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('sub_description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_tel', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Event Name', max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, choices=[('LA', 'USLA Pavilion'), ('LB', 'Irwin Inn Beach'), ('LC', "Crowe's Landing Docks"), ('LD', 'Multiple'), ('LE', None)], max_length=2)),
                ('unique_location', models.CharField(blank=True, max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('cost_has_hst', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='images/events/')),
                ('pdf_file', models.FileField(blank=True, upload_to='files/events/')),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program', to_field='name')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('total_available_spaces', models.PositiveIntegerField(default=0)),
                ('total_reserved_spaces', models.PositiveIntegerField(default=0)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('name', models.CharField(default=' Name', max_length=60, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, choices=[('LA', 'USLA Pavilion'), ('LB', 'Irwin Inn Beach'), ('LC', "Crowe's Landing Docks"), ('LD', 'Multiple'), ('LE', None)], max_length=2)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='usla', max_length=40)),
                ('site_desc', models.CharField(default='', max_length=80)),
                ('contact', models.EmailField(default='info@usla.ca', max_length=254)),
                ('facebook_link', models.URLField(blank=True)),
                ('logo_header_image', models.ImageField(blank=True, upload_to='images/site/')),
                ('logo_btm_image', models.ImageField(blank=True, upload_to='images/site/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UslaLocations',
            fields=[
                ('name', models.CharField(default='The Location Name', max_length=50, primary_key=True, serialize=False)),
                ('short_name', models.CharField(default='Abrv', max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='boardmember',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BoardPositions'),
        ),
    ]
