# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-01 16:36
from __future__ import unicode_literals

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
    ]
