# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:30
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(upload_to=app.models.get_upload_gallery_image_to_images)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EventGallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, upload_to=app.models.get_upload_news_item_to_files)),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_news_item_to_images)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramGalleryImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(upload_to=app.models.get_upload_gallery_image_to_images)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramGallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.BoardPositions')),
                ('committee_member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.CommitteeChairPositions')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='USLAGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=140)),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USLAGalleryPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(upload_to=app.models.get_upload_gallery_image_to_images)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.USLAGallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='is_annual_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programevent',
            name='is_annual_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=app.models.TwelveHourTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, default='url', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='programevent',
            name='start_time',
            field=app.models.TwelveHourTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='programgallery',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program'),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
    ]
