# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 00:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTopics',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'News Topics',
            },
        ),
        migrations.AlterModelOptions(
            name='frontpagelinks',
            options={'verbose_name_plural': 'Front Page Links'},
        ),
        migrations.AlterModelOptions(
            name='membershipsettings',
            options={'verbose_name_plural': 'Membership Settings'},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='contact_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message=b'Phone number invalid.', regex=b'^\\+?1?[\\d-]{9,18}$')]),
        ),
        migrations.AddField(
            model_name='program',
            name='pdf_link_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='general_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NewsTopics'),
        ),
    ]
