# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 03:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitememberprofile',
            old_name='email_forward',
            new_name='email',
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='cottage_address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='cottage_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='cottage_tel',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b'Phone number invalid.', regex=b'^\\+?1?[\\d-]{9,18}$')]),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='tel_num_bus',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b'Phone number invalid.', regex=b'^\\+?1?[\\d-]{9,18}$')]),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='township',
            field=models.CharField(blank=True, choices=[(b'LA', b'North Kawartha'), (b'LB', b'Douro-Dummer'), (b'LC', b'Other'), (b'LE', None)], max_length=2),
        ),
    ]
