# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_btm_image',
            field=models.ImageField(blank=True, upload_to='images/site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_header_image',
            field=models.ImageField(blank=True, upload_to='images/site/'),
        ),
    ]
