# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageLinks',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('link_text', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
