# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170607_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='programevent',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='programevent',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='unique_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programevent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='programevent',
            name='unique_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, choices=[(b'LA', b'USLA Pavilion'), (b'LB', b'Irwin Inn Beach'), (b'LC', b"Crowe's Landing Docks"), (b'LD', b'Multiple'), (b'LE', None)], max_length=2),
        ),
        migrations.AlterField(
            model_name='programevent',
            name='location',
            field=models.CharField(blank=True, choices=[(b'LA', b'USLA Pavilion'), (b'LB', b'Irwin Inn Beach'), (b'LC', b"Crowe's Landing Docks"), (b'LD', b'Multiple'), (b'LE', None)], max_length=2),
        ),
    ]
