# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-01 16:41
from __future__ import unicode_literals

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180301_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='UslaMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_forward', models.EmailField(blank=True, max_length=254)),
                ('tel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')])),
                ('cel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')])),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_members_to_images)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
