# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 03:20
from __future__ import unicode_literals

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180606_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='UslaPerson',
            fields=[
                ('usla_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b'Phone number invalid.', regex=b'^\\+?1?[\\d-]{9,18}$')])),
                ('cel_num', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b'Phone number invalid.', regex=b'^\\+?1?[\\d-]{9,18}$')])),
                ('image', models.ImageField(blank=True, upload_to=app.models.get_upload_usla_family_membership_images)),
                ('image_thumb', models.ImageField(blank=True, upload_to=app.models.get_upload_usla_family_membership_images)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
