# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170609_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
