# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170620_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeechairpositions',
            options={'verbose_name_plural': 'Committee Chair Positions'},
        ),
        migrations.AlterField(
            model_name='sitememberprofile',
            name='board_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BoardPositions'),
        ),
        migrations.AlterField(
            model_name='sitememberprofile',
            name='committee_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CommitteeChairPositions'),
        ),
    ]
