# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uslamember'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitememberprofile',
            name='cottage_address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='cottage_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
