# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170609_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='programevent',
            options={'ordering': ['start_date', 'start_time']},
        ),
    ]
