# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180301_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitememberprofile',
            old_name='email_forward',
            new_name='email',
        ),
    ]
