# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180301_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitememberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
