# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180302_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslaperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
