# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180302_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslaperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
