# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 15:42
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180302_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitememberprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sitememberprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.get_upload_usla_membership_images),
        ),
        migrations.AlterField(
            model_name='uslaperson',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='uslaperson',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.get_upload_usla_membership_images),
        ),
        migrations.AlterField(
            model_name='uslaperson',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
    ]
