# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180303_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uslaperson',
            old_name='id',
            new_name='usla_id',
        ),
    ]
