# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 16:33
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180303_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslaperson',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.get_upload_usla_family_membership_images),
        ),
    ]
