# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 15:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_uslaperson_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitememberprofile',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='country',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='sitememberprofile',
            name='tel_num_bus',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')]),
        ),
    ]
