# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180403_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitememberprofile',
            name='township',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
