# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sitememberprofile_township'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitememberprofile',
            name='township',
            field=models.CharField(blank=True, choices=[('LA', 'North Kawartha'), ('LB', 'Douro-Dummer'), ('LC', 'Other'), ('LE', None)], max_length=2),
        ),
    ]
