# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180404_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitememberprofile',
            name='cottage_tel',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?[\\d-]{9,18}$')]),
        ),
    ]
