# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sitememberprofile_cottage_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitememberprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
